# codecov.yml
coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 8%
    patch:
      default:
        target: 25%
        threshold: 0%
  ignore:
    - "src/main/java/seedu.address/ui/MainWindow.java"
    - "src/main/java/seedu.address/ui/PolicyCard.java"
    - "src/main/java/seedu.address/ui/PolicyListPanel.java"
    - "src/main/java/seedu.address/ui/ContractCard.java"
    - "src/main/java/seedu.address/ui/ContractListPanel.java"


