@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueContactList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-up-> "1" UniqueContractList
UniqueTagList -[hidden]down- UniqueContactList
UniqueTagList -[hidden]down- UniqueContactList

UniqueTagList -right-> "*" Tag
UniqueContactList -right-> Contact
UniqueContractList-right-> "*" Contract

Contact -up-> "*" Tag
Contact-up-> "*" Contract

Contact *--> Name
Contact *--> Phone
Contact *--> Email
Contact *--> Address
Contact *--> Nric
@enduml
